name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - dev

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  release:
    name: Release
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          fetch-depth: 0

      # Cambio a distribución temurin (puede ser microsoft)
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"   # o "microsoft"
          java-version: "21"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      # Limpieza profunda de cachés de Gradle
      - name: Clean compiler caches
        run: |
          rm -rf ~/.gradle/caches/
          rm -rf ~/.gradle/daemon/
          ./gradlew --stop

      - name: Publish shared module to Maven Local
        env:
          GITHUB_TOKEN: ${{ secrets.EXTEN_TOKEN }}
        run: ./gradlew :extensions:shared:publishToMavenLocal

      - name: Build patches
        env:
          GITHUB_TOKEN: ${{ secrets.EXTEN_TOKEN }}
        run: |
          ./gradlew clean generatePatchesFiles --no-configuration-cache \
            -x :extensions:spoof-signature:syncExtension \
            -x :extensions:spoof-wifi:syncExtension

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          fingerprint: ${{ vars.GPG_FINGERPRINT }}

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.EXTEN_TOKEN }}
        run: npm exec semantic-release

      - name: Upload EXRE to Release
        if: github.ref == 'refs/heads/master'
        uses: softprops/action-gh-release@v2
        with:
          files: patches/build/libs/*.EXRE
        env:
          GITHUB_TOKEN: ${{ secrets.EXTEN_TOKEN }}